name: marksorens
favicon: null
layout_spectrum: 0.24767
typography_spectrum: 0.39643
title: Businessing Daily
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.978356423554942
  lightness: 0.5631292143370956
  saturation: 0.2670601981226355
  rhythmicContrast: 0.13209069636650383
purpose: []
